steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest",
        "--region",
        "europe-west4",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "${_ACCOUNT_NAME}"
      ]
